### ISSUE TITLE
Can't get plugin to work with lazyvim

### ISSUE THREAD

**Issue by JonathanSiddle** [sidlatau/neotest-dart#14]
Hey,

This is probably not an issue with the plugin, but any help you can provide would be appreciated :) I am new to Neovim and trying to set up Flutter with lazyvim. I have got the status sidebar to display files with tests but it does not seem to pick up individual test, likewise if I put my curser in a test and try to run I get a notice 'no tests found'. 

I followed this guide to get set-up: https://www.lazyvim.org/extras/test/core, I managed to get Go tests working so I think the core-set up is OK. I have tried various combinations but this is what the plugin file currently looks like: 

```lua
{
    "nvim-neotest/neotest",
    dependencies = {
      "sidlatau/neotest-dart",
      "nvim-lua/plenary.nvim",
      "antoinemadec/FixCursorHold.nvim",
      "nvim-treesitter/nvim-treesitter",
    },
    opts = {
      adaters = {
        ["neotest-dart"] = {
          command = "flutter",
          use_lsp = true,
        },
      },
    },
  },
```

Any ideas what could be going wrong? 

Thanks

**Comment by sidlatau** [comment]
I am not using `lazyvim` distro, so no ideas. You may check my configuration, maybe that will be helpful: `https://github.com/sidlatau/dotfiles/blob/master/nvim/.config/nvim/lua/plugins/neotest.lua`.

**Comment by tst-038** [comment]
Same issue here
@JonathanSiddle Have you perhaps already found a solution?

**Comment by JonathanSiddle** [comment]
> Same issue here [@JonathanSiddle](https://github.com/JonathanSiddle) Have you perhaps already found a solution?

I do not have a solution to hand at the moment! I have continued doing some work with Flutter and Lazyvim though, if I get chance to workout and test the solution I will come back and post it for reference.

An alternative I used in the short-term is the web based Flutter-dev tools also include a debugging tool.

**Comment by tst-038** [comment]
@JonathanSiddle 

I have a forked repo where some things are fixed, 
Havent made a PR since its has its own problems and I currently dont really have the time to fix them.
Once I do I will take properly fix things ...
