### ISSUE TITLE
Cannot recognize blocTests

### ISSUE THREAD

**Issue by avatarnguyen** [sidlatau/neotest-dart#7]
This plugin won't recognize blocTest, f.e this one:

```dart
    blocTest<AuthBloc, AuthState>(
      '''
SHOULD emit [AuthState] authenticated after AuthenticationStatus changed to authenticated
      ''',
      build: () => authBloc,
      act: (bloc) => ...,
      expect: () => [
        ...
      ],
    );

```

I am wondering whether this could easily be fix by adding `blocTest` to line13 in file `lsp_outline_parser.lua` ?

```
 local _, _, test_name = element.name:find('[testWidgets,test, blocTest]%("(.+)"%)')
```

**Comment by avatarnguyen** [comment]
- The first approach with `lsp_outline_parser.lua` didn't work.

- 2nd approach with Treesitter is not working perfectly.

```    
(identifier) @testFunc (#any-of? @testFunc "test" "testWidgets" "blocTest")
```

the test is recognized and in success case the test also run through. But when I change my bloc test to a faulty one, it run until timeout and didn't display a correct error message.

**Comment by sidlatau** [comment]
I added the ability to configure custom test method names. Please try to add `custom_test_method_names 
 = {'blockTest'}` to your config, that may help. 

In general, it is not an ideal solution. LSP outline already provides all the needed information, it should be enough to mark with method `@isTest`. That's how VSCode works. I think it should be possible to implement this behavior in this plugin too, but that requires bigger refactoring.
